name: recetario
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.5+1
  path_provider: ^2.0.13
  image_picker: ^1.0.0
  provider: ^6.0.5
  persistent_bottom_nav_bar: ^5.0.2
  crypto: ^3.0.0
  file_picker: ^5.3.1
  open_filex: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icono.png
    - assets/fondo_bienvenida.jpg
    - assets/comida.jpg